const assert = require('assert');
const { labelPortion, validLabelRow } = require('../utils/label-foods');
const { createDiary, addFood, setLabelFood, toggleMeal, refreshDay, dateKey, saveDay, readDays, copyPlan } = require('../utils/tracker');
let storage = {}, fail = false, definition;
global.wx = { getStorageSync: k => storage[k], setStorageSync(k,v) { if (fail) throw new Error('full'); storage[k] = JSON.parse(JSON.stringify(v)); }, showToast() {}, switchTab() {} };
global.Page = value => { definition = value; };
// Synthetic label values for deterministic arithmetic, not a recommended product.
const label = { name: '测试豆浆', state: '即饮', unit: 'g', protein: '3', carbs: '2', fat: '1', calories: '121.336', energyUnit: 'kJ' };
const row = labelPortion(label, 300);
assert.deepStrictEqual([row.protein, row.carbs, row.fat, row.calories], [9,6,3,87]);
assert.ok(validLabelRow(row)); assert.ok(!validLabelRow({ ...row, protein: 10 }));
assert.throws(() => labelPortion({ ...label, fat: '' }, 300), /都需填写/);
assert.throws(() => labelPortion({ ...label, fat: -1 }, 300));
assert.throws(() => labelPortion({ ...label, fat: 'NaN' }, 300));
assert.throws(() => labelPortion(label, 0));
assert.equal(labelPortion({ ...label, calories: '' }, 300).calories, 87);
assert.equal(labelPortion({ ...label, unit: 'mL' }, 300).unit, 'mL');
let day = createDiary(dateKey());
day = addFood(day,0,'soyMilk',300); day = addFood(day,0,'oats',60);
assert.deepStrictEqual([day.meals[0].protein,day.meals[0].carbs,day.meals[0].fat,day.meals[0].calories],[18.8,44.9,8.9,332.4]);
assert.equal(day.consumed.protein,0);
day = toggleMeal(day,0); assert.equal(day.consumed.protein,18.8);
saveDay(day); assert.equal(refreshDay(readDays()[dateKey()]).consumed.carbs,44.9);
assert.throws(() => setLabelFood(day,0,0,label,300), /已经记录/);
day = toggleMeal(day,0); day = setLabelFood(day,0,0,label,300); saveDay(day);
assert.equal(readDays()[dateKey()].meals[0].foods[0].basis.protein,3);
const copied = copyPlan(day,'2025-01-01'); assert.equal(copied.diaryOnly,true); assert.equal(copied.meals[0].logged,false);
assert.equal(copied.meals[0].foods[0].basis.protein,3);
function page() { delete require.cache[require.resolve('../pages/today/index')]; require('../pages/today/index'); return { ...definition, data: JSON.parse(JSON.stringify(definition.data)), setData(patch) { for (const key of Object.keys(patch)) { const parts=key.split('.'); let target=this.data; parts.slice(0,-1).forEach(k=>target=target[k]); target[parts[parts.length-1]]=patch[key]; } } }; }
const ev = value => ({ detail: { value } }), tap = data => ({ currentTarget: { dataset: data } });
storage={}; const screen=page(); screen.onShow(); screen.startDiary(); assert.ok(screen.data.day.diaryOnly);
screen.openEditor(tap({meal:'0',add:'yes'})); screen.onFoodSearch(ev('豆浆')); assert.equal(screen.data.foodOptions.length,1);
screen.onSwapGrams(ev('300')); assert.equal(screen.data.editor.preview.protein,8.7); screen.applyEditor();
screen.openEditor(tap({meal:'0',add:'yes'})); screen.onFoodSearch(ev('燕麦')); screen.onSwapGrams(ev('60')); screen.applyEditor();
assert.equal(screen.data.day.meals[0].carbs,44.9);
screen.openEditor(tap({meal:'0',food:'0'})); screen.setEntryMode(tap({mode:'label'}));
screen.setData({'editor.form':label}); screen.onSwapGrams(ev('300'));
fail=true; screen.applyEditor(); assert.equal(screen.data.day.meals[0].foods[0].id,'soyMilk'); assert.ok(screen.data.editor);
fail=false; screen.applyEditor(); assert.equal(screen.data.day.meals[0].foods[0].id,'labelFood');
screen.toggleMeal(tap({meal:'0'})); screen.completeCheckin(); assert.equal(screen.data.habit.done,true);
const reopened=page(); reopened.onShow(); assert.equal(reopened.data.day.meals[0].foods[0].protein,9);
reopened.toggleMeal(tap({meal:'0'})); reopened.openEditor(tap({meal:'0',food:'0'})); assert.equal(reopened.data.editor.custom,true);
reopened.onLabelUnit(tap({unit:'mL'})); assert.equal(reopened.data.editor.grams,''); assert.equal(reopened.data.editor.preview,null);
console.log('Food diary: gram arithmetic, label units, blank meals, search, persistence, check-ins and failure recovery passed');
