const assert = require('assert');
const { statistics, monthCells, readCheckins, checkIn } = require('../utils/habits');
const { dateKey, previousDate } = require('../utils/tracker');
let storage = {}, fail = false;
global.wx = { getStorageSync: k => storage[k], setStorageSync: (k, v) => { if (fail) throw new Error('full'); storage[k] = JSON.parse(JSON.stringify(v)); }, showToast() {}, nextTick: fn => fn(), switchTab() {} };
const row = { meals: 1, weight: false };
assert.deepStrictEqual(readCheckins(), {});
const leap = { '2024-02-28': row, '2024-02-29': row, '2024-03-01': row };
assert.equal(statistics(leap, '2024-03-02').streak, 3);
assert.equal(statistics(leap, '2024-03-03').streak, 0);
assert.equal(statistics(leap, '2024-03-03').longest, 3);
assert.equal(statistics(leap, '2024-03-03').badges[0].earned, true);
assert.equal(statistics({ '2025-12-31': row, '2026-01-01': row }, '2026-01-01').streak, 2);
assert.equal(monthCells('2024-02', leap, '2024-02-29').filter(c => !c.blank).length, 29);
assert.equal(monthCells('2024-03', leap, '2024-03-01').filter(c => c.future).length, 30);
const today = dateKey();
assert.throws(() => checkIn(today), /先记录/);
assert.throws(() => checkIn(previousDate(today)), /日期/);
storage.weightHistoryV1 = [{ date: today, kg: 75 }];
fail = true; assert.throws(() => checkIn(today), /full/); assert.equal(storage.habitCheckinsV1, undefined);
fail = false; checkIn(today); assert.equal(readCheckins()[today].weight, true);
checkIn(today); assert.equal(Object.keys(readCheckins()).length, 1);
storage.weightHistoryV1 = []; checkIn(today); assert.equal(readCheckins()[today].weight, true); // Snapshot remains after editing source.
storage.habitCheckinsV1 = { bad: row }; assert.throws(readCheckins, /异常/); assert.throws(() => checkIn(today), /异常/);
assert.deepStrictEqual(storage.habitCheckinsV1, { bad: row });
storage = {};
let definition;
global.Page = value => { definition = value; };
function page(path) { delete require.cache[require.resolve(path)]; require(path); return { ...definition, data: JSON.parse(JSON.stringify(definition.data)), setData(patch) { Object.assign(this.data, patch); } }; }
const screen = page('../pages/today/index'); screen.onShow(); screen.completeCheckin(); assert.equal(screen.data.habit.done, false);
storage.weightHistoryV1 = [{ date: today, kg: 75 }]; screen.onShow(); assert.equal(screen.data.tasks.weight, true);
fail = true; screen.completeCheckin(); assert.equal(screen.data.habit.done, false);
fail = false; screen.completeCheckin(); assert.equal(screen.data.habit.done, true);
const reopened = page('../pages/today/index'); reopened.onShow(); assert.equal(reopened.data.habit.total, 1);
const progress = page('../pages/progress/index'); progress.onShow(); assert.equal(progress.data.cells.find(c => c.date === today).done, true);
progress.inspectCheckin({ currentTarget: { dataset: { date: today } } }); assert.ok(progress.data.selectedCheckin.includes('已记录体重'));
const month = progress.data.month; progress.changeMonth({ currentTarget: { dataset: { step: 1 } } }); assert.equal(progress.data.month, month);
progress.changeMonth({ currentTarget: { dataset: { step: -1 } } }); assert.notEqual(progress.data.month, month);
console.log('habit and check-in integration tests passed');
