const assert = require('assert');
const fs = require('fs');
const { FOODS, foodPortion, sumNutrition } = require('../utils/foods');
const { createDiary, addFood, toggleMeal, refreshDay, saveDay, readDays } = require('../utils/tracker');
const { labelPortion } = require('../utils/label-foods');
const storage = {};
global.wx = { getStorageSync: k => storage[k], setStorageSync: (k, v) => { storage[k] = JSON.parse(JSON.stringify(v)); } };
assert.equal(foodPortion('banana', 150).fiber, 3.9);
assert.equal(foodPortion('choySum', 200).fiber, 3);
assert.equal(foodPortion('broccoliBoiled', 100).fiber, 3.3);
assert.notEqual(FOODS.broccoli.fiber, FOODS.broccoliBoiled.fiber);
assert.equal(foodPortion('chickenRaw', 100).fiber, 0);
assert.equal(foodPortion('soyMilk', 100).fiber, null);
let day = addFood(createDiary('2026-09-22'), 0, 'banana', 150);
day = addFood(day, 0, 'choySum', 200);
assert.equal(day.planned.fiber, 6.9);
assert.equal(day.consumed.fiber, 0);
day = toggleMeal(day, 0);
assert.equal(day.consumed.fiber, 6.9);
saveDay(day);
assert.equal(refreshDay(readDays()['2026-09-22']).consumed.fiber, 6.9);
const backup = require('../utils/account-backup');
const { validateBackup } = require('../cloudfunctions/accountLogin/backup');
wx.removeStorageSync = key => { delete storage[key]; };
const snapshot = validateBackup(backup.collect());
delete storage.nutritionDaysV1;
backup.restore(snapshot);
assert.equal(refreshDay(readDays()['2026-09-22']).consumed.fiber, 6.9);
const old = JSON.parse(JSON.stringify(day));
delete old.meals[0].foods[0].fiber;
assert.equal(refreshDay(old).consumed.fiber, 6.9);
assert.equal(refreshDay(old).meals[0].foods[0].calories, day.meals[0].foods[0].calories);
const legacy = labelPortion({ name: '旧记录', state: '即食', unit: 'g', protein: 1, carbs: 2, fat: 3, calories: 39 }, 100);
const total = sumNutrition([{ foods: [foodPortion('banana', 150), legacy], ...sumNutrition([foodPortion('banana', 150), legacy]) }]);
assert.equal(total.fiber, 3.9); assert.equal(total.fiberMissing, 1); assert.ok(total.fiberLabel.includes('部分'));
let def; global.Page = p => { def = p; }; require('../pages/today/index');
const page = { ...def, data: JSON.parse(JSON.stringify(def.data)), setData(p) { for (const [key,value] of Object.entries(p)) { const bits=key.split('.'); let target=this.data; for (const bit of bits.slice(0,-1)) target=target[bit]; target[bits.at(-1)]=value; } } };
page.data.editor = { optionIndex: 0, modeIndex: 2, grams: '100' };
page.onFoodCategory({ currentTarget: { dataset: { category: 'fruits' } } });
assert.ok(page.data.foodOptions.length >= 15);
assert.ok(page.data.foodOptions.every(item => FOODS[item.id].category === 'fruits'));
page.onFoodSearch({ detail: { value: '奇异果' } }); assert.equal(page.data.editor.preview.id, 'kiwi');
page.onFoodCategory({ currentTarget: { dataset: { category: 'vegetables' } } });
page.onFoodSearch({ detail: { value: '菜心' } }); assert.equal(page.data.editor.preview.id, 'choySum');
page.onFoodSearch({ detail: { value: '不存在' } }); assert.equal(page.data.editor.preview, null);
assert.ok(!page.data.editor.error.includes('包装'));
for (const path of ['today','foods']) {
  const markup = fs.readFileSync(__dirname + '/../pages/' + path + '/index.wxml', 'utf8');
  assert.ok(!markup.includes('按包装录入'));
  assert.ok(!markup.includes('bindinput="onLabelField"'));
  assert.ok(!markup.includes('bindinput="onCustomMeatInput"'));
}
console.log('Produce and fiber: portions, partial totals, history, persistence, aliases and gram-only UI passed.');
