const assert = require('assert');
let storage = {}, modal, definition;
global.wx = { getStorageSync: key => storage[key], setStorageSync: (key, value) => { storage[key] = JSON.parse(JSON.stringify(value)); }, removeStorageSync: key => delete storage[key], showModal: value => { modal = value; }, showToast() {} };
const waist = require('../utils/waist');
const backup = require('../utils/account-backup');
const { validateBackup } = require('../cloudfunctions/accountLogin/backup');
assert.equal(waist.entry('2026-09-20', '72.34', '2026-09-28').cm, 72.3);
assert.throws(() => waist.entry('2026-09-29', 72, '2026-09-28'));
assert.throws(() => waist.entry('2026-09-20', '', '2026-09-28'));
storage.waistHistoryV1 = [{ date: '2026-09-20', cm: 74 }, { date: '2026-09-28', cm: 72 }];
assert.deepStrictEqual(waist.trend(waist.read(), '2026-09-28'), { latest: 72, change: -2, weekAverage: 72, weekCount: 1 });
const payload = backup.collect(); validateBackup(payload);
backup.remember('a', 1, payload);
assert.match(backup.status('a', { updatedAt: 1 }), /一致/);
storage.waistHistoryV1.push({ date: '2026-09-21', cm: 73 });
assert.match(backup.status('a', { updatedAt: 1 }), /尚未备份/);
assert.match(backup.status('b', { updatedAt: 1 }), /尚未确认/);
assert.match(backup.status('a', { updatedAt: 2 }), /尚未确认/);
backup.restore(payload); assert.equal(waist.read().length, 2);
backup.restore({ version: 1, data: {} }); assert.equal(waist.read().length, 0);
const tracker = require('../utils/tracker');
const { foodPortion } = require('../utils/foods');
global.Page = page => { definition = page; };
require('../pages/today/index');
const page = { ...definition, data: { day: tracker.createDiary(tracker.dateKey()) }, checkRollover() {}, persist(day) { this.data.day = day; }, report(error) { this.error = error; } };
page.data.day.meals[0].foods = [foodPortion('oats', 60)];
page.data.day.meals[1].foods = [foodPortion('rice', 100)];
page.confirmMealCopy(1, page.data.day, 0);
modal.success({ confirm: false }); assert.equal(page.data.day.meals[1].foods[0].id, 'rice');
page.confirmMealCopy(1, page.data.day, 0);
modal.success({ confirm: true }); assert.equal(page.data.day.meals[1].foods[0].id, 'oats');
page.confirmMealCopy(1, page.data.day, 0);
page.data.day.meals[1].logged = true;
modal.success({ confirm: true }); assert.match(page.error.message, /餐次已变化/);
console.log('progress update tests passed');
