const assert = require('assert');
const { calculateProfile } = require('../utils/health');
const { foodPortion } = require('../utils/foods');
const t = require('../utils/tracker');
const store = {};
global.wx = { getStorageSync: key => store[key], setStorageSync: (key, value) => { store[key] = JSON.parse(JSON.stringify(value)); } };
const profile = calculateProfile({ heightCm: 180, weight: 180, weightUnit: 'jin', age: 30, sex: 'male', activityLevel: 'moderate' });
assert.strictEqual(t.dateKey(new Date(2026, 0, 2, 0, 1)), '2026-01-02');
assert.strictEqual(t.previousDate('2026-01-01'), '2025-12-31');
assert.strictEqual(t.previousDate('2024-03-01'), '2024-02-29');
assert.strictEqual(t.validDate('2026-02-30'), false);
let day = t.createDay(profile, '2026-09-19');
assert.strictEqual(day.completed, 0);
assert.strictEqual(day.consumed.calories, 0);
day = t.toggleMeal(day, 0);
assert.strictEqual(day.consumed.calories, day.meals[0].calories);
assert.strictEqual(t.toggleMeal(day, 0).consumed.calories, 0);
assert.throws(() => t.replaceFood(day, 0, 0, 'rice', 100), /取消记录/);
assert.throws(() => t.addFood(day, 0, 'rice', 100), /取消记录/);
assert.throws(() => t.removeFood(day, 0, 0), /取消记录/);
const original = day.meals[1].foods[1];
const grams = t.replacementGrams(original, 'beefCooked', 'protein');
assert.ok(Math.abs(foodPortion('beefCooked', grams).protein - original.protein) < 0.1);
const oldTotal = day.planned.calories;
day = t.replaceFood(day, 1, 1, 'beefCooked', grams);
assert.notStrictEqual(day.planned.calories, oldTotal);
assert.strictEqual(day.consumed.calories, day.meals[0].calories);
assert.ok(Math.abs(day.meals[1].calories - day.meals[1].foods.reduce((sum, row) => sum + row.calories, 0)) < 0.01);
assert.throws(() => t.replacementGrams(original, 'oil', 'protein'), /替换/);
assert.throws(() => t.replaceFood(day, 1, 1, 'beefCooked', 0), /克数/);
day = t.addFood(day, 1, 'oil', 10);
const oilIndex = day.meals[1].foods.length - 1;
assert.strictEqual(day.meals[1].foods[oilIndex].calories, 88.4);
day = t.removeFood(day, 1, oilIndex);
const preserved = JSON.stringify(day.meals[0]);
const newGoal = calculateProfile({ ...profile.input, weight: 90, weightUnit: 'kg', goalChoice: 'gain' });
const updated = t.createDay(newGoal, day.date, day);
assert.strictEqual(JSON.stringify(updated.meals[0]), preserved);
assert.strictEqual(updated.target.calories, newGoal.targetCalories);
const nextDay = t.copyPlan(day, '2026-09-20');
assert.strictEqual(nextDay.completed, 0);
assert.strictEqual(nextDay.consumed.calories, 0);
assert.strictEqual(JSON.stringify(day.meals[0]), preserved);
const copiedMeal = t.copyMeal(day, 1, day, 0);
assert.strictEqual(copiedMeal.meals[1].logged, false);
assert.deepStrictEqual(copiedMeal.meals[1].foods.map(food => food.id), day.meals[0].foods.map(food => food.id));
assert.throws(() => t.copyMeal(day, 1, t.createDiary('2026-09-18'), 1), /没有食物/);
t.saveDay(day); t.saveDay(nextDay);
assert.strictEqual(Object.keys(t.readDays()).length, 2);
const trendDays = { '2026-09-19': day, '2026-09-20': t.toggleMeal(nextDay, 0) };
const nutrition = t.nutritionTrend(trendDays, '2026-09-20');
assert.strictEqual(nutrition.days, 2);
assert.strictEqual(nutrition.completeDays, 0);
assert.strictEqual(nutrition.calories, Math.round((day.consumed.calories + trendDays['2026-09-20'].consumed.calories) / 2 * 10) / 10);
assert.strictEqual(t.nutritionTrend({}, '2026-09-20').calories, null);
const excess = t.createDay(profile, '2026-09-21'); excess.target.protein = 1;
const logged = t.toggleMeal(excess, 0);
assert.strictEqual(logged.summary[1].remaining, 0);
assert.ok(logged.summary[1].over > 0);
assert.strictEqual(logged.summary[1].percent, 100);
store.nutritionDaysV1 = 'damaged';
assert.throws(() => t.saveDay(day), /无法读取/);
assert.strictEqual(store.nutritionDaysV1, 'damaged');
assert.deepStrictEqual(t.weightEntry('2026-09-19', '154', 'jin', '2026-09-19'), { date: '2026-09-19', kg: 77 });
assert.throws(() => t.weightEntry('2026-09-20', '77', 'kg', '2026-09-19'), /日期/);
assert.throws(() => t.weightEntry('2026-09-19', '', 'kg', '2026-09-19'), /体重/);
const trend = t.weightTrend([{ date: '2026-09-01', kg: 80 }, { date: '2026-09-13', kg: 78 }, { date: '2026-09-19', kg: 77 }], '2026-09-19');
assert.strictEqual(trend.weekAverage, 77.5);
assert.strictEqual(trend.weekCount, 2);
assert.strictEqual(trend.change, -3);
assert.strictEqual(t.weightTrend([]).latest, null);
console.log('Tracking: snapshots, swaps, meal copy, totals, history, persistence errors, date boundaries and trends passed.');
