// 每 100 g 可食部。来源为 USDA 官方 FDC / SR28，2026-09-22 核对。
// 固定条目 ID；不覆盖已有食物，以保留历史快照。
const EXPANDED_PRODUCE = {
  "tomato": {
    "name": "番茄",
    "aliases": "西红柿",
    "state": "生重·可食部",
    "category": "vegetables",
    "calories": 18,
    "protein": 0.88,
    "carbs": 3.89,
    "fat": 0.2,
    "fiber": 1.2,
    "sourceId": "170457",
    "sourceDescription": "Tomatoes, red, ripe, raw, year round average",
    "note": "烹调前称可食部分生重，不是做熟后的重量；用油和其他食材另计。"
  },
  "cucumberPeeled": {
    "name": "黄瓜（去皮）",
    "aliases": "青瓜",
    "state": "生重·可食部",
    "category": "vegetables",
    "calories": 10,
    "protein": 0.59,
    "carbs": 2.16,
    "fat": 0.16,
    "fiber": 0.7,
    "sourceId": "169225",
    "sourceDescription": "Cucumber, peeled, raw",
    "note": "去皮后称生重，不含两端弃去部分。"
  },
  "cabbage": {
    "name": "包菜",
    "aliases": "卷心菜 圆白菜 甘蓝",
    "state": "生重·可食部",
    "category": "vegetables",
    "calories": 25,
    "protein": 1.28,
    "carbs": 5.8,
    "fat": 0.1,
    "fiber": 2.5,
    "sourceId": "169975",
    "sourceDescription": "Cabbage, raw",
    "note": "烹调前称可食部分生重，不是做熟后的重量；用油和其他食材另计。"
  },
  "lettuce": {
    "name": "绿叶生菜",
    "aliases": "生菜",
    "state": "生重·可食部",
    "category": "vegetables",
    "calories": 15,
    "protein": 1.36,
    "carbs": 2.87,
    "fat": 0.15,
    "fiber": 1.3,
    "sourceId": "169249",
    "sourceDescription": "Lettuce, green leaf, raw",
    "note": "烹调前称可食部分生重，不是做熟后的重量；用油和其他食材另计。"
  },
  "eggplant": {
    "name": "茄子",
    "aliases": "",
    "state": "生重·可食部",
    "category": "vegetables",
    "calories": 25,
    "protein": 0.98,
    "carbs": 5.88,
    "fat": 0.18,
    "fiber": 3,
    "sourceId": "169228",
    "sourceDescription": "Eggplant, raw",
    "note": "烹调前称可食部分生重，不是做熟后的重量；用油和其他食材另计。"
  },
  "daikon": {
    "name": "白萝卜",
    "aliases": "萝卜",
    "state": "生重·可食部",
    "category": "vegetables",
    "calories": 18,
    "protein": 0.6,
    "carbs": 4.1,
    "fat": 0.1,
    "fiber": 1.6,
    "sourceId": "168451",
    "sourceDescription": "Radishes, oriental, raw",
    "note": "烹调前称可食部分生重，不是做熟后的重量；用油和其他食材另计。"
  },
  "greenPepper": {
    "name": "青甜椒",
    "aliases": "青椒 柿子椒",
    "state": "生重·可食部",
    "category": "vegetables",
    "calories": 20,
    "protein": 0.86,
    "carbs": 4.64,
    "fat": 0.17,
    "fiber": 1.7,
    "sourceId": "170427",
    "sourceDescription": "Peppers, sweet, green, raw",
    "note": "烹调前称可食部分生重，不是做熟后的重量；用油和其他食材另计。"
  },
  "redPepper": {
    "name": "红甜椒",
    "aliases": "彩椒 灯笼椒",
    "state": "生重·可食部",
    "category": "vegetables",
    "calories": 26,
    "protein": 0.99,
    "carbs": 6.03,
    "fat": 0.3,
    "fiber": 2.1,
    "sourceId": "170108",
    "sourceDescription": "Peppers, sweet, red, raw",
    "note": "烹调前称可食部分生重，不是做熟后的重量；用油和其他食材另计。"
  },
  "celery": {
    "name": "西芹",
    "aliases": "芹菜",
    "state": "生重·可食部",
    "category": "vegetables",
    "calories": 14,
    "protein": 0.69,
    "carbs": 2.97,
    "fat": 0.17,
    "fiber": 1.6,
    "sourceId": "169988",
    "sourceDescription": "Celery, raw",
    "note": "烹调前称可食部分生重，不是做熟后的重量；用油和其他食材另计。"
  },
  "zucchini": {
    "name": "西葫芦",
    "aliases": "角瓜",
    "state": "生重·可食部",
    "category": "vegetables",
    "calories": 17,
    "protein": 1.21,
    "carbs": 3.11,
    "fat": 0.32,
    "fiber": 1,
    "sourceId": "169291",
    "sourceDescription": "Squash, summer, zucchini, includes skin, raw",
    "note": "烹调前称可食部分生重，不是做熟后的重量；用油和其他食材另计。"
  },
  "whiteMushroom": {
    "name": "白蘑菇",
    "aliases": "口蘑 双孢菇",
    "state": "生重·可食部",
    "category": "vegetables",
    "calories": 22,
    "protein": 3.09,
    "carbs": 3.26,
    "fat": 0.34,
    "fiber": 1,
    "sourceId": "169251",
    "sourceDescription": "Mushrooms, white, raw",
    "note": "烹调前称可食部分生重，不是做熟后的重量；用油和其他食材另计。"
  },
  "shiitake": {
    "name": "鲜香菇",
    "aliases": "香菇",
    "state": "生重·可食部",
    "category": "vegetables",
    "calories": 34,
    "protein": 2.24,
    "carbs": 6.79,
    "fat": 0.49,
    "fiber": 2.5,
    "sourceId": "169242",
    "sourceDescription": "Mushrooms, shiitake, raw",
    "note": "烹调前称可食部分生重，不是做熟后的重量；用油和其他食材另计。"
  },
  "apricot": {
    "name": "杏子",
    "aliases": "杏",
    "state": "生重·可食部",
    "category": "fruits",
    "calories": 48,
    "protein": 1.4,
    "carbs": 11.12,
    "fat": 0.39,
    "fiber": 2,
    "sourceId": "USDA-SR28-09021",
    "sourceDescription": "Apricots, raw",
    "sourceUrl": "https://www.ars.usda.gov/ARSUserFiles/80400535/Data/SR/SR28/reports/sr28fg09.pdf",
    "note": "只称吃下的可食部分，去掉不吃的皮、核和籽；不适用于果干、果汁或糖渍制品。"
  },
  "blackberry": {
    "name": "黑莓",
    "aliases": "",
    "state": "生重·可食部",
    "category": "fruits",
    "calories": 43,
    "protein": 1.39,
    "carbs": 9.61,
    "fat": 0.49,
    "fiber": 5.3,
    "sourceId": "USDA-SR28-09042",
    "sourceDescription": "Blackberries, raw",
    "sourceUrl": "https://www.ars.usda.gov/ARSUserFiles/80400535/Data/SR/SR28/reports/sr28fg09.pdf",
    "note": "只称吃下的可食部分，去掉不吃的皮、核和籽；不适用于果干、果汁或糖渍制品。"
  },
  "blueberry": {
    "name": "蓝莓",
    "aliases": "",
    "state": "生重·可食部",
    "category": "fruits",
    "calories": 57,
    "protein": 0.74,
    "carbs": 14.49,
    "fat": 0.33,
    "fiber": 2.4,
    "sourceId": "USDA-SR28-09050",
    "sourceDescription": "Blueberries, raw",
    "sourceUrl": "https://www.ars.usda.gov/ARSUserFiles/80400535/Data/SR/SR28/reports/sr28fg09.pdf",
    "note": "只称吃下的可食部分，去掉不吃的皮、核和籽；不适用于果干、果汁或糖渍制品。"
  },
  "cherry": {
    "name": "甜樱桃",
    "aliases": "樱桃 车厘子",
    "state": "生重·可食部",
    "category": "fruits",
    "calories": 63,
    "protein": 1.06,
    "carbs": 16.01,
    "fat": 0.2,
    "fiber": 2.1,
    "sourceId": "USDA-SR28-09070",
    "sourceDescription": "Cherries, sweet, raw",
    "sourceUrl": "https://www.ars.usda.gov/ARSUserFiles/80400535/Data/SR/SR28/reports/sr28fg09.pdf",
    "note": "只称吃下的可食部分，去掉不吃的皮、核和籽；不适用于果干、果汁或糖渍制品。"
  },
  "durian": {
    "name": "榴莲",
    "aliases": "",
    "state": "生重·可食部",
    "category": "fruits",
    "calories": 147,
    "protein": 1.47,
    "carbs": 27.09,
    "fat": 5.33,
    "fiber": 3.8,
    "sourceId": "USDA-SR28-09422",
    "sourceDescription": "Durian, raw or frozen",
    "sourceUrl": "https://www.ars.usda.gov/ARSUserFiles/80400535/Data/SR/SR28/reports/sr28fg09.pdf",
    "note": "只称吃下的可食部分，去掉不吃的皮、核和籽；不适用于果干、果汁或糖渍制品。"
  },
  "grapefruit": {
    "name": "西柚（红肉／粉肉）",
    "aliases": "葡萄柚",
    "state": "生重·可食部",
    "category": "fruits",
    "calories": 42,
    "protein": 0.77,
    "carbs": 10.66,
    "fat": 0.14,
    "fiber": 1.6,
    "sourceId": "USDA-SR28-09112",
    "sourceDescription": "Grapefruit, raw, pink and red, all areas",
    "sourceUrl": "https://www.ars.usda.gov/ARSUserFiles/80400535/Data/SR/SR28/reports/sr28fg09.pdf",
    "note": "只称吃下的可食部分，去掉不吃的皮、核和籽；不适用于果干、果汁或糖渍制品。"
  },
  "grapes": {
    "name": "葡萄（红／绿）",
    "aliases": "提子 红提 青提",
    "state": "生重·可食部",
    "category": "fruits",
    "calories": 69,
    "protein": 0.72,
    "carbs": 18.1,
    "fat": 0.16,
    "fiber": 0.9,
    "sourceId": "USDA-SR28-09132",
    "sourceDescription": "Grapes, red or green (European type, such as Thompson seedless), raw",
    "sourceUrl": "https://www.ars.usda.gov/ARSUserFiles/80400535/Data/SR/SR28/reports/sr28fg09.pdf",
    "note": "只称吃下的可食部分，去掉不吃的皮、核和籽；不适用于果干、果汁或糖渍制品。"
  },
  "lemon": {
    "name": "柠檬（去皮）",
    "aliases": "柠檬",
    "state": "生重·可食部",
    "category": "fruits",
    "calories": 29,
    "protein": 1.1,
    "carbs": 9.32,
    "fat": 0.3,
    "fiber": 2.8,
    "sourceId": "USDA-SR28-09150",
    "sourceDescription": "Lemons, raw, without peel",
    "sourceUrl": "https://www.ars.usda.gov/ARSUserFiles/80400535/Data/SR/SR28/reports/sr28fg09.pdf",
    "note": "只称吃下的可食部分，去掉不吃的皮、核和籽；不适用于果干、果汁或糖渍制品。"
  },
  "lychee": {
    "name": "荔枝",
    "aliases": "",
    "state": "生重·可食部",
    "category": "fruits",
    "calories": 66,
    "protein": 0.83,
    "carbs": 16.53,
    "fat": 0.44,
    "fiber": 1.3,
    "sourceId": "USDA-SR28-09164",
    "sourceDescription": "Litchis, raw",
    "sourceUrl": "https://www.ars.usda.gov/ARSUserFiles/80400535/Data/SR/SR28/reports/sr28fg09.pdf",
    "note": "只称吃下的可食部分，去掉不吃的皮、核和籽；不适用于果干、果汁或糖渍制品。"
  },
  "longan": {
    "name": "鲜龙眼",
    "aliases": "桂圆 龙眼",
    "state": "生重·可食部",
    "category": "fruits",
    "calories": 60,
    "protein": 1.31,
    "carbs": 15.14,
    "fat": 0.1,
    "fiber": 1.1,
    "sourceId": "USDA-SR28-09172",
    "sourceDescription": "Longans, raw",
    "sourceUrl": "https://www.ars.usda.gov/ARSUserFiles/80400535/Data/SR/SR28/reports/sr28fg09.pdf",
    "note": "只称吃下的可食部分，去掉不吃的皮、核和籽；不适用于果干、果汁或糖渍制品。"
  },
  "cantaloupe": {
    "name": "网纹甜瓜（通用参考）",
    "aliases": "哈密瓜 甜瓜",
    "state": "生重·可食部",
    "category": "fruits",
    "calories": 34,
    "protein": 0.84,
    "carbs": 8.16,
    "fat": 0.19,
    "fiber": 0.9,
    "sourceId": "USDA-SR28-09181",
    "sourceDescription": "Melons, cantaloupe, raw",
    "sourceUrl": "https://www.ars.usda.gov/ARSUserFiles/80400535/Data/SR/SR28/reports/sr28fg09.pdf",
    "note": "只称吃下的可食部分，去掉不吃的皮、核和籽；不适用于果干、果汁或糖渍制品。采用网纹甜瓜通用参考，不代表所有哈密瓜品种。"
  },
  "honeydew": {
    "name": "蜜瓜",
    "aliases": "白兰瓜 甜瓜",
    "state": "生重·可食部",
    "category": "fruits",
    "calories": 36,
    "protein": 0.54,
    "carbs": 9.09,
    "fat": 0.14,
    "fiber": 0.8,
    "sourceId": "USDA-SR28-09184",
    "sourceDescription": "Melons, honeydew, raw",
    "sourceUrl": "https://www.ars.usda.gov/ARSUserFiles/80400535/Data/SR/SR28/reports/sr28fg09.pdf",
    "note": "只称吃下的可食部分，去掉不吃的皮、核和籽；不适用于果干、果汁或糖渍制品。"
  },
  "nectarine": {
    "name": "油桃",
    "aliases": "",
    "state": "生重·可食部",
    "category": "fruits",
    "calories": 44,
    "protein": 1.06,
    "carbs": 10.55,
    "fat": 0.32,
    "fiber": 1.7,
    "sourceId": "USDA-SR28-09191",
    "sourceDescription": "Nectarines, raw",
    "sourceUrl": "https://www.ars.usda.gov/ARSUserFiles/80400535/Data/SR/SR28/reports/sr28fg09.pdf",
    "note": "只称吃下的可食部分，去掉不吃的皮、核和籽；不适用于果干、果汁或糖渍制品。"
  },
  "persimmon": {
    "name": "柿子",
    "aliases": "甜柿",
    "state": "生重·可食部",
    "category": "fruits",
    "calories": 70,
    "protein": 0.58,
    "carbs": 18.59,
    "fat": 0.19,
    "fiber": 3.6,
    "sourceId": "USDA-SR28-09263",
    "sourceDescription": "Persimmons, japanese, raw",
    "sourceUrl": "https://www.ars.usda.gov/ARSUserFiles/80400535/Data/SR/SR28/reports/sr28fg09.pdf",
    "note": "只称吃下的可食部分，去掉不吃的皮、核和籽；不适用于果干、果汁或糖渍制品。"
  },
  "plum": {
    "name": "李子",
    "aliases": "李",
    "state": "生重·可食部",
    "category": "fruits",
    "calories": 46,
    "protein": 0.7,
    "carbs": 11.42,
    "fat": 0.28,
    "fiber": 1.4,
    "sourceId": "USDA-SR28-09279",
    "sourceDescription": "Plums, raw",
    "sourceUrl": "https://www.ars.usda.gov/ARSUserFiles/80400535/Data/SR/SR28/reports/sr28fg09.pdf",
    "note": "只称吃下的可食部分，去掉不吃的皮、核和籽；不适用于果干、果汁或糖渍制品。"
  },
  "pomegranate": {
    "name": "石榴",
    "aliases": "",
    "state": "生重·可食部",
    "category": "fruits",
    "calories": 83,
    "protein": 1.67,
    "carbs": 18.7,
    "fat": 1.17,
    "fiber": 4,
    "sourceId": "USDA-SR28-09286",
    "sourceDescription": "Pomegranates, raw (1 )",
    "sourceUrl": "https://www.ars.usda.gov/ARSUserFiles/80400535/Data/SR/SR28/reports/sr28fg09.pdf",
    "note": "只称吃下的可食部分，去掉不吃的皮、核和籽；不适用于果干、果汁或糖渍制品。"
  },
  "raspberry": {
    "name": "树莓",
    "aliases": "覆盆子",
    "state": "生重·可食部",
    "category": "fruits",
    "calories": 52,
    "protein": 1.2,
    "carbs": 11.94,
    "fat": 0.65,
    "fiber": 6.5,
    "sourceId": "USDA-SR28-09302",
    "sourceDescription": "Raspberries, raw",
    "sourceUrl": "https://www.ars.usda.gov/ARSUserFiles/80400535/Data/SR/SR28/reports/sr28fg09.pdf",
    "note": "只称吃下的可食部分，去掉不吃的皮、核和籽；不适用于果干、果汁或糖渍制品。"
  },
  "asparagus": {
    "name": "芦笋",
    "aliases": "",
    "state": "生重·可食部",
    "category": "vegetables",
    "calories": 20,
    "protein": 2.2,
    "carbs": 3.88,
    "fat": 0.12,
    "fiber": 2.1,
    "sourceId": "USDA-SR28-11011",
    "sourceDescription": "Asparagus, raw",
    "sourceUrl": "https://www.ars.usda.gov/ARSUserFiles/80400535/Data/SR/SR28/reports/sr28fg11.pdf",
    "note": "烹调前称可食部分生重，不是做熟后的重量；用油和其他食材另计。"
  },
  "cabbageBoiled": {
    "name": "包菜（水煮）",
    "aliases": "卷心菜 圆白菜",
    "state": "熟重·水煮沥水",
    "category": "vegetables",
    "calories": 23,
    "protein": 1.27,
    "carbs": 5.51,
    "fat": 0.06,
    "fiber": 1.9,
    "sourceId": "USDA-SR28-11110",
    "sourceDescription": "Cabbage, cooked, boiled, drained, without salt",
    "sourceUrl": "https://www.ars.usda.gov/ARSUserFiles/80400535/Data/SR/SR28/reports/sr28fg11.pdf",
    "note": "水煮熟后沥水称重，不含额外油脂；不适用于炒制或油炸。"
  },
  "cauliflowerBoiled": {
    "name": "菜花（水煮）",
    "aliases": "花椰菜",
    "state": "熟重·水煮沥水",
    "category": "vegetables",
    "calories": 23,
    "protein": 1.84,
    "carbs": 4.11,
    "fat": 0.45,
    "fiber": 2.3,
    "sourceId": "USDA-SR28-11136",
    "sourceDescription": "Cauliflower, cooked, boiled, drained, without salt",
    "sourceUrl": "https://www.ars.usda.gov/ARSUserFiles/80400535/Data/SR/SR28/reports/sr28fg11.pdf",
    "note": "水煮熟后沥水称重，不含额外油脂；不适用于炒制或油炸。"
  },
  "enoki": {
    "name": "鲜金针菇",
    "aliases": "金针菇",
    "state": "生重·可食部",
    "category": "vegetables",
    "calories": 37,
    "protein": 2.66,
    "carbs": 7.81,
    "fat": 0.29,
    "fiber": 2.7,
    "sourceId": "USDA-SR28-11950",
    "sourceDescription": "Mushrooms, enoki, raw (1 )",
    "sourceUrl": "https://www.ars.usda.gov/ARSUserFiles/80400535/Data/SR/SR28/reports/sr28fg11.pdf",
    "note": "烹调前称可食部分生重，不是做熟后的重量；用油和其他食材另计。"
  },
  "okra": {
    "name": "秋葵",
    "aliases": "",
    "state": "生重·可食部",
    "category": "vegetables",
    "calories": 33,
    "protein": 1.93,
    "carbs": 7.45,
    "fat": 0.19,
    "fiber": 3.2,
    "sourceId": "USDA-SR28-11278",
    "sourceDescription": "Okra, raw",
    "sourceUrl": "https://www.ars.usda.gov/ARSUserFiles/80400535/Data/SR/SR28/reports/sr28fg11.pdf",
    "note": "烹调前称可食部分生重，不是做熟后的重量；用油和其他食材另计。"
  },
  "spinachBoiled": {
    "name": "菠菜（水煮）",
    "aliases": "",
    "state": "熟重·水煮沥水",
    "category": "vegetables",
    "calories": 23,
    "protein": 2.97,
    "carbs": 3.75,
    "fat": 0.26,
    "fiber": 2.4,
    "sourceId": "USDA-SR28-11458",
    "sourceDescription": "Spinach, cooked, boiled, drained, without salt",
    "sourceUrl": "https://www.ars.usda.gov/ARSUserFiles/80400535/Data/SR/SR28/reports/sr28fg11.pdf",
    "note": "水煮熟后沥水称重，不含额外油脂；不适用于炒制或油炸。"
  }
};
module.exports = { EXPANDED_PRODUCE };
